export const projects = [
  {
    slug: 'ikiminapass',
    name: 'IkiminaPass',
    role: 'Backend & Project Lead',
    description: 'Architected and led the full backend of IkiminaPass, a fintech platform digitising Rwanda\'s community savings groups (Ibimina). Built on NestJS, TypeScript, and PostgreSQL with Prisma ORM, the system handles automated contribution tracking, loan management, and group treasury operations. Integrated IntouchPay and RSwitch/MoMo for mobile money processing, built a USSD interface for feature-phone access, and wired Africa\'s Talking SMS alongside FCM for dual-channel real-time alerts — making the platform accessible to members across all device types.',
    visibility: 'public',
    domains: ['Fintech', 'Community Savings'],
    tags: ['Payment Integration', 'USSD', 'Notifications'],
    techStack: ['NestJS', 'TypeScript', 'PostgreSQL', 'Prisma', 'IntouchPay', 'USSD', 'Africa\'s Talking', 'FCM'],
    image: '/ikimina.png',
    links: {
      code: 'https://github.com/tresormu',
      demo: 'https://ikimina-web.vercel.app/',
      report: undefined,
      leaderboard: undefined,
    },
    featured: true,
  },
  {
    slug: 'mamacare',
    name: 'MamaCare',
    role: 'Backend Developer & Project Lead',
    description: 'Built a backend system to support maternal health tracking and care coordination for expectant mothers in Rwanda. Designed RESTful APIs for appointment scheduling, health record management, and pregnancy milestone tracking. Integrated push notification delivery via FCM to keep mothers and healthcare providers aligned on checkups and alerts. Focused on reliability and low-bandwidth accessibility to ensure the platform serves users in both urban and rural contexts.',
    visibility: 'public',
    domains: ['Health', 'Maternal Care'],
    tags: ['Healthcare', 'API Design', 'Real-time'],
    techStack: ['Node.js', 'Express', 'REST API', 'FCM', 'PostgreSQL'],
    image: '/mamacare.png',
    links: {
      code: 'https://github.com/tresormu',
      demo: 'https://hackthon-web-phi.vercel.app/',
      report: undefined,
      leaderboard: undefined,
    },
    featured: true,
  },
  {
    slug: 'theyouthcontest',
    name: 'TheYouthContest',
    role: 'Full-Stack Developer',
    description: 'Designed and built the full-stack infrastructure digitalising debate championship operations from registration to results. Implemented Role-Based Access Control (RBAC) to enforce secure, role-specific access for admins, judges, and participants. Built and deployed a clean React frontend with optimised data fetching, and engineered a Node.js backend handling tournament brackets, speaker points, and match scheduling — eliminating the manual overhead of paper-based competition management.',
    visibility: 'public',
    domains: ['EdTech', 'Tournament Management'],
    tags: ['RBAC', 'React', 'Node.js'],
    techStack: ['React', 'Node.js', 'RBAC', 'REST API'],
    image: '/Youthcontest.png',
    links: {
      code: 'https://github.com/tresormu',
      demo: 'https://youthcont-fn.vercel.app/',
      report: undefined,
      leaderboard: undefined,
    },
    featured: true,
  },
  {
    slug: 'job-portal',
    name: 'Job Portal',
    role: 'Backend & Project Lead',
    description: 'Led the full development lifecycle of a recruitment platform connecting employers and job seekers. Designed MongoDB schemas and built backend APIs for job listings, applications, and user role management. Implemented JWT-based authentication with protected routes and role-based access control separating employer and applicant workflows. Managed architecture decisions, task distribution, version control, and deployment end to end.',
    visibility: 'public',
    domains: ['Recruitment', 'HR Tech'],
    tags: ['Job Board', 'Authentication', 'Role Management'],
    techStack: ['MongoDB', 'Express', 'JWT', 'RBAC', 'Node.js'],
    image: '/jopPortal.png',
    links: {
      code: 'https://github.com/tresormu',
      demo: 'https://job-portal-front-topaz.vercel.app/',
      report: undefined,
      leaderboard: undefined,
    },
    featured: true,
  },
  {
    slug: 'bdifferent',
    name: 'BDifferent',
    role: 'Full-Stack Developer',
    description: 'Built a full-stack e-commerce platform with a Node.js and Express backend supporting product, user, and category management with image upload. Architected optimised MongoDB schemas with efficient data relationships to keep product queries fast at scale. Integrated frontend and backend via Axios for a decoupled, scalable architecture, and enforced type-safe API requests using Zod schema validation middleware.',
    visibility: 'public',
    domains: ['E-commerce', 'Retail'],
    tags: ['E-commerce', 'Image Upload', 'API Design'],
    techStack: ['Node.js', 'Express', 'MongoDB', 'Axios', 'Zod'],
    image: '/BDifferent.png',
    links: {
      code: 'https://github.com/tresormu',
      demo: 'https://full-ecommerce-sigma.vercel.app/',
      report: undefined,
      leaderboard: undefined,
    },
    featured: true,
  },
  {
    slug: 'shieldkids',
    name: 'ShieldKids',
    role: 'Full-Stack Developer & Lead (KLab)',
    description: 'Led backend development of ShieldKids, a child safety application built during a six-month engagement at KLab. Owned architecture, sprint execution, and stakeholder demos end to end. Implemented persistent WebSockets for real-time location tracking and geofence breach alerts, and architected RESTful APIs covering authentication, device registration, app controls, and screen time enforcement. Managed all PR reviews, resolved integration conflicts, and delivered every sprint from planning through demo.',
    visibility: 'private',
    domains: ['Child Safety', 'Real-Time Tracking'],
    tags: ['WebSockets', 'Geofencing', 'Real-time'],
    techStack: ['WebSockets', 'Node.js', 'REST API', 'Geofencing'],
    image: '/shieldkids.png',
    links: {
      code: undefined,
      demo: undefined,
      report: undefined,
      leaderboard: undefined,
    },
    featured: false,
  },
]

export function getProjectBySlug(slug: string) {
  return projects.find(project => project.slug === slug)
}
